I3_PKGS=(
  ungoogled-chromium-bin
  ttf-iosevkaterm-nerd
  ttf-iosevka-nerd
  noto-fonts-emoji
  autotiling
  i3status
  i3blocks
  i3-wm

  zathura-pdf-poppler
  pavucontrol
  brave-bin
  alacritty
  redshift
  vesktop
  poppler
  zathura
  ffmpeg
  arandr
  picom
  xclip
  yazi
  rofi
  wget
  feh
)

NVIM_PKGS=(
  ripgrep
  neovim
  nodejs
  yazi
  tmux
  fzf
  git
  gcc
  npm
  fd
)

ZSH_PKGS=(
  zsh

  unzip
  tmux
  curl
  wget
  fzf
  git
  fd
)

DEV_PKGS=(
  git
  btop
  tmux
  wget
  github-cli
)
